package main

import (
	"fmt"
	"log"
	"os"
)

func generateHTML_edit(listFile string) {

	f, err := os.Create(listFile)
	if err != nil {
		log.Fatalln("CreateFile:", listFile, err.Error())
	}
	defer f.Close()

	str := fmt.Sprintf(`<!-- Code generated by codegen from SQL table %s -->
<div class="main-section__title">
  <i class="icon icon--xs icon--blue-grey icon--circled mdi mdi-auto-fix"></i>
  %s Details
</div>

<h3 class="main-section__title">%s Details</h3>

<form name="edit%s.form" ng-submit="edit%s.submit()">

<formly-form model="edit%s.%s" fields="edit%s.formFields">

<div flex-container="row" flex-align="end" item="1">
    <div flex-item>
      <button type="button" class="btn btn--l btn--blue-grey btn--raised" ng-click="edit%s.abort()" lx-ripple>Back</button>
    </div>
    <div flex-item>
      <button type="submit" 
              class="btn btn--l btn--blue btn--raised" 
              lx-ripple>
                Save Details
      </button>
    </div>
</div>

</formly-form>
</form>


<div class="card">
  <lx-tabs>
    <lx-tab heading="Notes">
      <div class="card">
        <textarea ng-wig="edit%s.%s.Notes"></textarea>
      </div>    
    </lx-tab>

    <lx-tab heading="Documents">
    </lx-tab>

		<!-- TODO: Add any more tabs you want in here -->

    <lx-tab heading="Activity Log">
      <div class="data-table-container">
        <table class="data-table">
          <thead>
            <tr>
              <th> Event</th>
              <th> Date</th>
              <th> Description</th>
              <th> IP Address</th>
              <th> By</th>
            </tr>
          </thead>
          <tbody>
            <tr class="data-table"
                ng-class="edit%s.logClass(l)"           
                ng-repeat="l in edit%s.logs">
                  <td>{{l.Type}}</td>
                  <td>{{l.Logdate}}</td>
                  <td>{{l.Descr}}</td>
                  <td>{{l.IP}}</td>
                  <td>{{l.Username}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </lx-tab>

  </lx-tabs>
</div>

`,
		sqltable,
		Tablename,
		Tablename,
		Tablename,
		Tablename,
		Tablename, tablename, Tablename,
		Tablename,
		Tablename, tablename,
		Tablename,
		Tablename)

	f.WriteString(str)
	f.Sync()
}
